@host = http://localhost:5299

POST {{host}}/notes
Content-Type: application/json

{
	"title": "Todo1",
	"description": "This is my first todo.."
}

###

# GET {{host}}/Notes/0659bde3-bb85-4602-950b-89b6053febc8