@host = http://localhost:5299

POST {{host}}/notes
Content-Type: application/json

{
	"title": "Todo",
	"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
}

###

# GET {{host}}/Notes/0659bde3-bb85-4602-950b-89b6053febc8