@id = 8bd3c04f-8c2b-4d33-a5b5-81e9cf339370

PUT http://localhost:5299/notes/{{id}}
Content-Type: application/json

{
	"title": "Todo1",
	"description": "This is my updated 4 todo..",
	"createdDate": "2024-01-26T01:19:50.668759Z"
}