@host = http://localhost:5299
@id = b478fd21-2ddc-4f87-9ac6-68296940a041

PUT {{host}}/notes/{{id}}
Content-Type: application/json

{
	"title": "Todo1",
	"description": "This is my updated 11 todo..",
	"createdDate": "2024-01-26T01:19:50.668759Z"
}