@host = http://localhost:5299
@id = e29f28cf-8473-49ac-83a6-eb704ed940de

PUT {{host}}/notes/{{id}}
Content-Type: application/json

{
	"title": "Todo1",
	"description": "This is my updated 5 todo..",
	"createdDate": "2024-01-26T01:19:50.668759Z"
}